# Site settings
title: Travel Blog
email: funtravel@gmail.com
description: A fun blog about traveling
baseurl: "/travel-blog"
twitter_username:  stvnrlnd
avatar: "https://pbs.twimg.com/profile_images/682591484340781057/rq5B5G3V.jpg" # Set footer avatar
paginate: 3

# Build settings
markdown: kramdown
permalink: /:title

# Default Settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: "Steven Roland" # Set default author name
      categories: "places"
      layout: "post"
      comments: true
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
